### ISSUE TITLE
Revert color to default setting

### ISSUE THREAD

**Issue by alexey-danilov** [rgh36167/FfxDarkenBackground#1]
When I first installed the add-on, I wanted to experiment with background settings other than default. But later on I realized that default played rather nicely with redshift filter - but unfortunately there was no way to revert to it. Background color menu offers only predefined set of colors, none of which is to my liking. I've tried to reinstall add-on, but it's last settings were persisted somewhere. Is there a way to revert to default, or to set a custom color?

**Comment by alexey-danilov** [comment]
To answer my own question: it seems that this setting can be changed (and reverted to default) via about:config

**Comment by rgh36167** [comment]
Thanks for the report. The simple-prefs ui is a bit too simple for many purposes, I don't see any better way to do it than what you found.

But it occurs to me that the default is fine tuned for the redshift filter and won't work well for the other two filters. So there could be three separate default background colors for the three filters or  instead of a particular RGB color it could be  a gray value which is transformed by the particular filter the user chooses.
